// Pending changes (REQ-027.7): everything on this branch that has not landed
// yet, in the order work travels — uncommitted drafts, then commits ahead of
// the default branch, then the forge. Self-healing: the scratch file carries a
// per-run stamp and is discarded at the end.
import { expect, test } from '@playwright/test';

test.describe.configure({ mode: 'serial' });

const REPO = 'trading-specs';
const H = { 'X-SpecQuill': '1' };

test('an edit shows up as pending and disappears once committed', async ({ page, request }) => {
  const stamp = Date.now().toString(36);
  const path = `requirements/scratch-pending-${stamp}.md`;
  const branch = ((await (await request.post(`/api/repos/${REPO}/workspace`, { headers: H, data: {} })).json()) as
    { branch: string }).branch;

  await request.put(`/api/repos/${REPO}/files/${path}?branch=${encodeURIComponent(branch)}`, {
    headers: H,
    data: { content: `---\ntype: Requirement\nid: REQ-${stamp}\ntitle: Scratch ${stamp}\nstatus: draft\n---\n\n# Scratch\n`, baseSha: '' },
  });

  await page.goto(`/p/${REPO}/b/${encodeURIComponent(branch)}/changes`);
  await expect(page.getByRole('heading', { name: 'Pending changes' })).toBeVisible();
  // the file is listed as uncommitted, classified into its family
  await expect(page.getByText(path)).toBeVisible();
  await expect(page.getByText('1 requirement', { exact: true }).first()).toBeVisible();
  // and the section links onward to the committed history
  await expect(page.getByText('Change history →')).toBeVisible();

  // commit it: it leaves "Uncommitted" and appears ahead of main
  await request.post(`/api/repos/${REPO}/commit?branch=${encodeURIComponent(branch)}`, {
    headers: H, data: { message: `test: scratch ${stamp}` },
  });
  await page.reload();
  await expect(page.getByText('working tree clean — nothing to commit')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Ahead of main' })).toBeVisible();
  // the OKF index.md regenerated by the commit mentions the path too
  await expect(page.getByText(path).first()).toBeVisible();

  // cleanup: drop the scratch document again
  await request.delete(`/api/repos/${REPO}/files/${path}?branch=${encodeURIComponent(branch)}`, { headers: H });
  await request.post(`/api/repos/${REPO}/commit?branch=${encodeURIComponent(branch)}`, {
    headers: H, data: { message: `test: drop scratch ${stamp}` },
  });
});
